version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: "github-actions"
    target-branch: master
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
